// Canonical list of Colyseus message types used by the client
// Centralized here so role-based handlers and pages can share them safely.

export const MSG = {
  // Core round + state
  ROUND_STATE_UPDATE: "ROUND_STATE_UPDATE",
  ROUND_STARTED: "ROUND_STARTED",
  ROUND_ENDED: "ROUND_ENDED",
  QUESTION_UPDATE: "QUESTION_UPDATE",
  TIMER_UPDATE: "TIMER_UPDATE",
  TEAM_UPDATE: "TEAM_UPDATE",
  GOLD_UPDATE: "GOLD_UPDATE",

  // Scoring / match lifecycle
  ROUND_SCORE: "ROUND_SCORE",
  ROUND_SCORE_UPDATE: "ROUND_SCORE_UPDATE",
  TEAM_SCORE_UPDATE: "TEAM_SCORE_UPDATE",
  PLAYER_SCORE_UPDATE: "PLAYER_SCORE_UPDATE",
  MATCH_OVER: "MATCH_OVER",
  MATCH_RESET: "MATCH_RESET",

  // Cards / effects
  CARD_CAST: "CARD_CAST",
  CARD_RULES_UPDATE: "CARD_RULES_UPDATE",

  // Moderation
  MODERATION_UPDATE: "MODERATION_UPDATE",

  // Room / system
  ROOM_ID: "ROOM_ID",
  ERROR: "ERROR",

  // Team assembly / lobby-like messages
  TEAM_JOINED: "TEAM_JOINED",
  TEAM_LEFT: "TEAM_LEFT",
  AVAILABLE_TEAMS: "AVAILABLE_TEAMS",
  TEAM_SETTINGS_UPDATE: "TEAM_SETTINGS_UPDATE",
  MATCH_START: "MATCH_START",
  LOBBY_UPDATE: "LOBBY_UPDATE",

  // Student-specific flows
  SUGGESTION: "SUGGESTION",
  ANSWER_UPDATE: "ANSWER_UPDATE",
  LOCK: "LOCK",
  WRITER_ROTATED: "WRITER_ROTATED",
  WRITER_TRANSFERRED: "WRITER_TRANSFERRED",
  ROUND_DATA: "ROUND_DATA",
  XP_EARNED: "XP_EARNED"
};


